#pragma once

#include "VmfDocument.hpp"

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <string_view>
#include <unordered_set>
#include <utility>
#include <vector>

namespace hammer::vmf {

enum class ObjectType { Solid, Entity };

struct ObjectRef
{
    ObjectType type{ObjectType::Solid};
    int id{-1};

    bool operator==(const ObjectRef&) const = default;
};

struct Vec3
{
    double x{0.0};
    double y{0.0};
    double z{0.0};
};

// Mirrors Camera3D::CAMSTRUCT: a saved 2D-view camera (eye position and
// look-at target), as created by the Camera tool and stored in the VMF
// "cameras" block.
struct CameraDef
{
    Vec3 eye{};
    Vec3 lookAt{};
};

struct TextureAxis
{
    Vec3 direction{};
    double shift{0.0};
    double scale{0.25};
};

struct DisplacementVertex
{
    Vec3 position{};
    // CCoreDispInfo::GenerateDispSurfNormals output. Source stores the averaged
    // normal without normalizing it a second time after CalcNormalFromEdges.
    Vec3 normal{0.0, 0.0, 1.0};
    // Source/Hammer CMapDisp render data generated by CalcDispSurfCoords and
    // GenerateDispSurfTangentSpaces. textureU/V remain in pre-normalized VMF
    // pixel space so render backends can divide by the loaded primary VTF size.
    double textureU{0.0};
    double textureV{0.0};
    Vec3 tangentS{1.0, 0.0, 0.0};
    Vec3 tangentT{0.0, 1.0, 0.0};
    // Source's VERTEXALPHATEXBLENDFACTOR receives 255 - CMapDisp::m_Alpha.
    double blendAlpha{0.0};
};

struct FaceGeometry
{
    int sideId{-1};
    std::string material;
    Vec3 normal{};
    TextureAxis uAxis{};
    TextureAxis vAxis{};
    // CMapFace::texture.nLightmapScale, the luxel size in world units. Hammer
    // defaults new faces to 16 (g_pGameConfig->GetDefaultLightmapScale()).
    int lightmapScale{16};
    std::vector<std::size_t> vertices;
    bool displacement{false};
    int displacementPower{0};
    std::vector<DisplacementVertex> displacementVertices;
    std::vector<std::size_t> displacementIndices;
};

struct BrushGeometry
{
    ObjectRef object;
    int id{-1};
    int ownerEntityId{-1};
    std::vector<Vec3> vertices;
    std::vector<std::pair<std::size_t, std::size_t>> edges;
    std::vector<FaceGeometry> faces;
    // Mirrors CMapSolid::HasDisp (hammer/mapsolid.cpp): true when ANY side of
    // this solid carries a dispinfo chunk.
    bool hasDisplacement{false};
};

// Hammer hides the non-displaced sides of a displacement solid in the 3D views.
// CMapSolid::Render3D computes
//     bMaskFaces = pDoc->IsDispSolidDrawMask() && HasDisp();
// and then skips every face for which !pFace->HasDisp(). CMapDoc::SelectFace
// applies the same mask so those hidden sides cannot be picked either. The
// toggle (CMapDoc::OnToggleDispSolidMask) defaults to true and only issues
// MAPVIEW_UPDATE_ONLY_3D, so the 2D wireframe views are deliberately unmasked.
bool isFaceMaskedByDisplacementSolid(const BrushGeometry& brush, const FaceGeometry& face,
                                     bool maskEnabled);



enum class ProjectedSurfaceKind { Decal, Overlay };

struct ProjectedSurfaceVertex
{
    Vec3 position{};
    Vec3 normal{0.0, 0.0, 1.0};
    double u{0.0};
    double v{0.0};
};

struct ProjectedSurface
{
    std::string material;
    ProjectedSurfaceKind kind{ProjectedSurfaceKind::Decal};
    // Triangle list. Every consecutive group of three vertices is one clipped
    // piece of the decal/overlay projected onto a brush or displacement face.
    std::vector<ProjectedSurfaceVertex> triangles;
};

struct EntityMarker
{
    ObjectRef object{ObjectType::Entity, -1};
    int id{-1};
    std::string classname;
    std::string targetName;
    Vec3 origin;
    Vec3 angles; // Raw Source pitch, yaw, roll from the VMF angles key
    bool hasPitchOverride{false};
    double pitchOverride{0.0};
    bool reversePitch{false}; // Exact Hammer lightprop render rule

    Vec3 renderAngles() const
    {
        Vec3 result = angles;
        if (hasPitchOverride) result.x = pitchOverride;
        if (reversePitch) result.x = -result.x;
        return result;
    }
    std::vector<std::pair<std::string, std::string>> properties;
    // Hammer stores info_overlay helper state in a nested overlaydata block.
    // Keep it separate from ordinary entity keyvalues so VMF properties remain
    // lossless while the renderer can consume the helper data directly.
    std::vector<std::pair<std::string, std::string>> overlayProperties;
    std::vector<ProjectedSurface> projectedSurfaces;
    // Solid ids whose faces the projected surfaces above were clipped onto.
    // Lets an incremental edit skip re-clipping entities whose source brushes
    // did not change (see projectedEntityDependsOnSolids).
    std::vector<int> projectedSourceSolidIds;
    Vec3 sizeMinimum{-8.0, -8.0, -8.0};
    Vec3 sizeMaximum{8.0, 8.0, 8.0};
    // World-space corners used for point-entity selection and transform handles.
    // Model helpers use transformed studio-model bounds; sprites use their image
    // dimensions; plain point entities fall back to the FGD size helper.
    std::array<Vec3, 8> selectionCorners{};
    bool hasSelectionCorners{false};
    std::array<int, 3> displayColor{108, 220, 108};
    std::string description;
    std::string model;
    int skin{0};
    // Source prop animation state. Sequence names are resolved lazily against
    // the cached MDL sequence table; a numeric sequence takes precedence.
    std::string animationSequence;
    int animationSequenceIndex{-1};
    double animationPlaybackRate{1.0};
    // A negative cycle means use the editor animation clock. A non-negative
    // value freezes the prop at that normalized sequence cycle.
    double animationCycle{-1.0};
    bool animateModel{false};
    std::string sprite;
};

struct ToneMapSettings
{
    // Source/TF2 defaults. env_tonemap_controller changes these at runtime,
    // usually from logic_auto OnMapSpawn outputs.
    double scale{1.0};
    double autoExposureMin{0.5};
    double autoExposureMax{2.0};
    double rate{1.0};
    double bloomScale{1.0};
    bool customAutoExposure{false};
    bool customBloomScale{false};
};

struct ColorCorrectionDefinition
{
    std::string filename;
    Vec3 origin{};
    Vec3 minimum{};
    Vec3 maximum{};
    double minFalloff{0.0};
    double maxFalloff{1000.0};
    double weight{1.0};
    bool enabled{true};
    bool volume{false};
};

struct Scene
{
    std::vector<BrushGeometry> brushes;
    std::vector<EntityMarker> entities;
    std::string skyName;
    // worldspawn "detailvbsp" and "detailmaterial": the detail-object
    // dictionary VBSP compiles this map's detail props from, and the material
    // whose atlas every detail sprite is cut out of. VBSP defaults the former
    // to "detail.vbsp" when the key is absent (FindDetailVBSPName).
    std::string detailVbspName;
    std::string detailMaterial;
    Vec3 minimum{};
    Vec3 maximum{};
    bool hasBounds{false};
    ToneMapSettings toneMap{};
    std::vector<ColorCorrectionDefinition> colorCorrections;

    // --- Incremental-update lineage --------------------------------------
    //
    // Render backends cache GPU buffers built from a Scene. Keying those caches
    // on the Scene's address is wrong twice over: a fresh Scene forces a full
    // re-upload even when one brush moved, and an in-place update reuses a
    // stale cache. These fields describe how this Scene differs from the one it
    // was derived from, so a backend can keep everything it already uploaded
    // and rebuild only the changed objects.
    //
    //   revision      unique, monotonically increasing id for this state.
    //   baseRevision  the revision this state was derived from, or 0 when the
    //                 scene was built from scratch (no reusable predecessor).
    //   changedSolidIds / changedEntityIds
    //                 exactly the objects that differ from baseRevision.
    std::uint64_t revision{0};
    std::uint64_t baseRevision{0};
    std::vector<int> changedSolidIds;
    std::vector<int> changedEntityIds;

    // Recent incremental steps, oldest first and bounded. Each entry records
    // the revision it advanced FROM and the objects that step changed. A
    // render cache whose revision matches any step's baseRevision can catch up
    // incrementally with the union of that step's and all later steps' ids -
    // essential when several edit steps land between two paints of a view
    // (every drag does this), which would otherwise fail the single-step
    // baseRevision check and force a full rebuild per frame.
    struct LineageStep
    {
        std::uint64_t baseRevision{0};
        std::vector<int> solidIds;
        std::vector<int> entityIds;
    };
    std::vector<LineageStep> lineageSteps;

    // Mark this state as having no reusable predecessor. Callers that mutate a
    // Scene outside rebuildSceneObjects (projected decal/overlay regeneration,
    // for instance) must call this so caches do a full rebuild.
    void invalidateLineage();
};

// Allocates the next process-wide unique Scene::revision.
std::uint64_t nextSceneRevision();

Scene buildScene(const Document& document);

// The geometry buildScene would produce for one "solid" block. Exposed so
// callers that already know which solids they care about (selection bounds,
// displacement painting) do not have to intersect the planes of every solid in
// the map to look at one of them.
BrushGeometry buildSolidGeometry(const Block& solid, int ownerEntityId = -1);

// buildScene restricted to the given solid ids: brushes are identical to the
// ones the full build would produce (including ownerEntityId and displacement
// tessellation) and everything else - entity markers, sky, tone map, color
// correction - is omitted. Scene bounds cover only the requested solids.
Scene buildSceneForSolids(const Document& document, const std::unordered_set<int>& solidIds);

// Fast path for interactive edits - dragging, resizing, rotating, displacement
// painting - which change a known set of objects and never create or destroy
// any. The listed solids and entity markers are rebuilt from the document and
// everything else is carried over from "previous", which for a drag of a few
// solids replaces a whole-map plane-intersection pass with a handful of solids.
//
// The result is what buildScene(document) would have returned. Whenever that
// cannot be guaranteed - an id is missing from the previous scene, a solid
// stopped forming a valid brush, or a changed entity feeds the scene-wide
// tone-map/color-correction state - this falls back to a full buildScene.
Scene rebuildSceneObjects(const Document& document, const Scene& previous,
                          const std::unordered_set<int>& changedSolidIds,
                          const std::unordered_set<int>& changedEntityIds);

// rebuildSceneObjects without the whole-scene copy: "scene" is updated in
// place and keeps its address, so a document that shares it with render
// backends does not have to hand out a new Scene per interactive edit. On
// success the scene's lineage records "scene.baseRevision" and the changed
// ids; on any fallback the scene is fully rebuilt and its lineage is cleared.
void rebuildSceneObjectsInPlace(const Document& document, Scene& scene,
                                const std::unordered_set<int>& changedSolidIds,
                                const std::unordered_set<int>& changedEntityIds);

std::string normalizeMaterialPath(std::string_view material);
bool isToolMaterialPath(std::string_view material);
std::vector<std::string> toolMaterialPaths(const Scene& scene);

// --- Tool-texture visibility ------------------------------------------------
//
// Hammer's originals hide whole objects through auto visgroups; there is no
// per-face hide in CVisGroup. This port's View > Tool Textures menu is keyed on
// materials instead, which are a per-FACE property, so the semantics are:
//
//   * A face is hidden when its material normalizes to a "tools/" path that is
//     in the hidden set. Hidden faces are never drawn and never pickable, in
//     either the 2D or the 3D views (matching CMapDoc::SelectFace, which
//     refuses to pick faces the 3D view does not draw).
//   * A SOLID is hidden only when EVERY one of its faces is hidden. That is the
//     closest analogue to the original's whole-object visgroup hide: a solid
//     built entirely from a hidden tool material (a nodraw block, a trigger, a
//     clip brush) disappears and stops being selectable by click or box, while
//     a world brush that merely has nodraw on its back sides stays visible and
//     selectable in 2D and only loses those individual faces in 3D.
//   * Hidden solids are dropped from the selection when visibility changes,
//     mirroring CSelection::RemoveInvisibles.
bool isMaterialHiddenByToolTextures(std::string_view material,
                                    const std::unordered_set<std::string>& hiddenToolTextures);
bool isFaceHiddenByToolTextures(const FaceGeometry& face,
                                const std::unordered_set<std::string>& hiddenToolTextures);
bool isBrushHiddenByToolTextures(const BrushGeometry& brush,
                                 const std::unordered_set<std::string>& hiddenToolTextures);

// --- Billboarded sprite sizing ----------------------------------------------
//
// Single source of truth for the world-space size a point entity's sprite
// billboard is drawn at. The hardware renderer, the 3D ray pick, and the 2D
// helper drawing/picking all call this so a sprite's selection box always hugs
// what is actually on screen.
struct BillboardSize
{
    double width{0.0};
    double height{0.0};
};

BillboardSize billboardSpriteSize(const EntityMarker& entity, int imageWidth, int imageHeight);

} // namespace hammer::vmf
