#!/usr/bin/env python3
from __future__ import annotations

from collections import Counter
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
HAMMER = ROOT / "src" / "hammer"

patterns = {
    "MFC headers": re.compile(r"#\s*include\s*[<\"]afx(?:win|ext|ole|odlgs|disp|db|dao|dtctl|cmn|priv|templ)\.h", re.I),
    "MFC classes": re.compile(r"\bC(?:Wnd|Dialog|View|FrameWnd|PropertyPage|PropertySheet|FormView|MDI\w*|WinApp|ControlBar|ListBox|ComboBox|TreeCtrl|Button|Edit|Menu|DC|Bitmap|Pen|Brush|ImageList)\b"),
    "MFC message maps": re.compile(r"\b(?:BEGIN_MESSAGE_MAP|END_MESSAGE_MAP|ON_[A-Z_]+)\b"),
    "Windows headers": re.compile(r"#\s*include\s*[<\"](?:windows|mmsystem|shellapi|shlobj|commctrl)\.h", re.I),
    "Win32 types/APIs": re.compile(r"\b(?:HWND|HDC|HANDLE|HBITMAP|DWORD|WPARAM|LPARAM|LRESULT|QueryPerformanceCounter|MessageBox|CreateProcess|RegOpenKey)\b"),
    "Direct3D": re.compile(r"\b(?:Direct3D|IDirect3D|D3D\w*)\b"),
    "Windows DLL names": re.compile(r"[A-Za-z0-9_]+\.dll\b", re.I),
}

files = [p for p in HAMMER.rglob("*") if p.suffix.lower() in {".cpp", ".c", ".h", ".hpp"}]
counts: Counter[str] = Counter()
affected: dict[str, set[Path]] = {name: set() for name in patterns}

for path in files:
    text = path.read_text(errors="ignore")
    for name, pattern in patterns.items():
        matches = pattern.findall(text)
        counts[name] += len(matches)
        if matches:
            affected[name].add(path.relative_to(ROOT))

cpp_files = [p for p in files if p.suffix.lower() in {".cpp", ".c"}]
portable = [
    Path("src/hammer/clock.cpp"),
    Path("src/hammer/noise.cpp"),
    Path("src/hammer/viewersettings.cpp"),
    Path("src/hammer/blockarray.h"),
]

lines = [
    "# Linux/Qt6 source audit",
    "",
    "Generated by `scripts/audit-source.py` from the supplied source tree.",
    "",
    f"- Hammer C/C++ source and header files scanned: **{len(files)}**",
    f"- Translation units scanned: **{len(cpp_files)}**",
    f"- Original files enabled in the Linux target: **{len(portable)}**",
    "",
    "## Dependency counts",
    "",
    "| Dependency | Matches | Affected files |",
    "|---|---:|---:|",
]
for name in patterns:
    lines.append(f"| {name} | {counts[name]} | {len(affected[name])} |")

lines += [
    "",
    "## First directly compiled files",
    "",
]
lines += [f"- `{path.as_posix()}`" for path in portable]
lines += [
    "",
    "## Port order",
    "",
    "1. Portable runtime and container utilities.",
    "2. VMF parsing/writing plus portable selection, transforms, deletion, properties, and undo (complete for the adapter layer).",
    "3. Original CMapClass/CMapDoc ownership and creation/resize/rotate tools.",
    "4. ToolManager integration and full Qt viewport event routing.",
    "5. OpenGL material/model rendering and Source filesystem mounting.",
    "6. Remaining tools, dialogs, compile/run integration, and platform services.",
    "",
    "The counts are lexical indicators rather than a claim that every match requires a separate rewrite.",
]

(ROOT / "PORTING_AUDIT.md").write_text("\n".join(lines) + "\n")
print(ROOT / "PORTING_AUDIT.md")
